### ISSUE TITLE
ImportError: cannot import name _thread , Need  help

### ISSUE THREAD

**Issue by KevinHu2014** [scrapinghub/slackbot#102]
Need help with this problem , thanks.
`Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from slackbot.bot import Bot
  File "/usr/local/lib/python2.7/site-packages/slackbot/bot.py", line 9, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread`

**Comment by KevinHu2014** [comment]
I find the solution by adding
`import sys
sys.path.insert(1,'/Library/Python/2.7/site-packages')
`
http://stackoverflow.com/questions/27630114/matplotlib-issue-on-os-x-importerror-cannot-import-name-thread
