### ISSUE TITLE
Keep getting "[Errno 110] Connection timed out" when python run.py

### ISSUE THREAD

**Issue by roperi** [scrapinghub/slackbot#112]
Is it normal? Or is it just me?

```
Traceback (most recent call last):
  File "run.py", line 34, in main
    bot.run()
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/slackbot/bot.py", line 34, in run
    self._client.rtm_connect()
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/slackbot/slackclient.py", line 42, in rtm_connect
    self.parse_slack_login_data(reply)
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/slackbot/slackclient.py", line 63, in parse_slack_login_data
    self.websocket = create_connection(self.login_data['url'])
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/websocket/_core.py", line 489, in create_connection
    websock.connect(url, **options)
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/websocket/_core.py", line 216, in connect
    options.pop('socket', None))
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/websocket/_http.py", line 67, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/home/user/.virtualenvs/slackbot/lib/python2.7/site-packages/websocket/_http.py", line 109, in _open_socket
    sock.connect(address)
  File "/usr/local/opt/python-2.7.9/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 110] Connection timed out

```

**Comment by roperi** [comment]
I'm going to close this because I haven't had any problems anymore. I might have done something wrong. Apologies.
