### ISSUE TITLE
AttributeError: 'module' object has no attribute 'parse_header'

### ISSUE THREAD

**Issue by ohaz** [scrapinghub/slackbot#12]
When I follow the tutorial on the github page I get the following error when doing bot = Bot():
Traceback (most recent call last):

```
  File "main.py", line 10, in <module>
    main()
  File "main.py", line 6, in main
    bot = Bot()
  File "/usr/lib/python2.7/site-packages/slackbot/bot.py", line 25, in __init__
    bot_emoji = settings.BOT_EMOJI if hasattr(settings, 'BOT_EMOJI') else None
  File "/usr/lib/python2.7/site-packages/slackbot/slackclient.py", line 34, in __init__
    self.rtm_connect()
  File "/usr/lib/python2.7/site-packages/slackbot/slackclient.py", line 37, in rtm_connect
    reply = self.webapi.rtm.start().body
  File "/usr/lib/python2.7/site-packages/slacker/__init__.py", line 369, in start
    return self.get('rtm.start')
  File "/usr/lib/python2.7/site-packages/slacker/__init__.py", line 62, in get
    return self._request(requests.get, api, **kwargs)
  File "/usr/lib/python2.7/site-packages/slacker/__init__.py", line 51, in _request
    **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    return self.build_response(request, resp)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 214, in build_response
    response.encoding = get_encoding_from_headers(response.headers)
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 317, in get_encoding_from_headers
    content_type, params = cgi.parse_header(content_type)
AttributeError: 'module' object has no attribute 'parse_header'
```

**Comment by lins05** [comment]
Can you run this in your python interpreter?

``` python
>>> import cgi
>>> print cgi.__file__
>>> dir(cgi)
```

**Comment by ohaz** [comment]
```
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgi
>>> print cgi.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__file__'
>>> dir(cgi)
['__doc__', '__name__', '__path__']
>>> 
```

**Comment by lins05** [comment]
:open_mouth: that's strange.

``` python
>>> dir(cgi)
['FieldStorage', 'FormContent', 'FormContentDict', 'InterpFormContentDict', 'MiniFieldStorage', 'StringIO', 'SvFormContentDict', 'UserDict', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__version__', '_parseparam', 'attrgetter', 'catch_warnings', 'dolog', 'escape', 'filterwarnings', 'initlog', 'log', 'logfile', 'logfp', 'maxlen', 'mimetools', 'nolog', 'os', 'parse', 'parse_header', 'parse_multipart', 'parse_qs', 'parse_qsl', 'print_arguments', 'print_directory', 'print_environ', 'print_environ_usage', 'print_exception', 'print_form', 'rfc822', 'sys', 'test', 'urllib', 'urlparse', 'valid_boundary', 'warn']
>>> 
```

I wonder what's your linux distro and how do you install python?

**Comment by ohaz** [comment]
Arch Linux 64 bit, installed via pacman

**Comment by dangra** [comment]
I'm on archlinux 64bits too and everything is normal:

```
$ python2 -c 'import cgi; print(cgi)'
<module 'cgi' from '/usr/lib/python2.7/cgi.pyc'>

$ python3 -c 'import cgi; print(cgi)'
<module 'cgi' from '/usr/lib/python3.4/cgi.py'>

$ python2
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgi
>>> print(cgi.__path__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__path__'
>>> print(cgi.__file__)
/usr/lib/python2.7/cgi.pyc
>>> print(cgi.parse_header)
<function parse_header at 0x7f4f1b456b18>
```

**Comment by ohaz** [comment]
okay, seems to be a ****ed up installation on my end

**Comment by xjcl** [comment]
I installed python3.9 with the deadsnakes repo as follows:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update --allow-insecure-repositories
sudo apt-get install python3.9* --allow-unauthenticated
```

`cgi.__file__` prints something very weird

```➜  pyces python3.9                   
Python 3.9.9 (main, Nov 16 2021, 03:05:18) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgi
>>> pring(cgi.__file__)
<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>NameError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 3.9.9: /usr/bin/python3.9<br>Tue Jan  4 03:29:23 2022</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///home/jan/Dropbox/py/pyces/<stdin>">/home/jan/Dropbox/py/pyces/&lt;stdin&gt;</a> in <strong>&lt;module&gt;</strong></td></tr>
<tr><td></td></tr></table><p><strong>NameError</strong>: name 'pring' is not defined
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
("name 'pring' is not defined",)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=
&lt;built-in method with_traceback of NameError object&gt;


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
NameError: name 'pring' is not defined

-->

>>> dir(cgi)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'cgi', 'cgitb']
```

I've been trying for hours to run a very simple script using multiple computers and Python versions. Python installs are such a mess and my pip always breaks. The only option I see now is to write a Dockerfile which basically installs its own operating system just to run ~100 lines of code... smh smh

**Comment by xjcl** [comment]
Any advice on how to fix this? I installed Python 3.9 like so:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update --allow-insecure-repositories
sudo apt-get install python3.9* --allow-unauthenticated
```

and I get OP's error if I try to install anything with pip (`$ python3.9 -m pip install pip`)

**Comment by xjcl** [comment]
I am getting this on my other computer as well now, for example when running johnnydep. Everything works when I run johnnydep in the terminal, but I get this weird exception when calling it in PyCharm with 
```
p = subprocess.run(["/usr/local/bin/johnnydep", wheel], capture_output=True, text=True)
```

where wheel is any string, for example `pip-audit`

To summarize:
- Python 3.9.10, Linux Mint 
- johnnydist from command line is fine
- file with subprocess call to johnnydist, when run in terminal, is fine
- file with subprocess call to johnnydist, when run in PyCharm, throws

**Comment by xjcl** [comment]
Now I feel stupid, I just had a file called `cgi.py` in my random scripts directory and PyCharm added it to my `PYTHONPATH` while the terminal did not. Sigh.
