### ISSUE TITLE
Getting TypeError: list() got an unexpected keyword argument 'cursor' from starting app

### ISSUE THREAD

**Issue by s905060** [scrapinghub/slackbot#231]
```
 File "/usr/local/lib/python3.9/dist-packages/slackbot/bot.py", line 20, in __init__
    self._client = SlackClient(
  File "/usr/local/lib/python3.9/dist-packages/slackbot/slackclient.py", line 60, in __init__
    self.rtm_connect()
  File "/usr/local/lib/python3.9/dist-packages/slackbot/slackclient.py", line 65, in rtm_connect
    self.parse_slack_login_data(reply)
  File "/usr/local/lib/python3.9/dist-packages/slackbot/slackclient.py", line 87, in parse_slack_login_data
    self.parse_user_data(self.list_users())
  File "/usr/local/lib/python3.9/dist-packages/slackbot/slackclient.py", line 78, in list_users
    return webapi_generic_list(self.webapi, 'users', 'members')
  File "/usr/local/lib/python3.9/dist-packages/slackbot/slackclient.py", line 30, in webapi_generic_list
    response = getattr(webapi, resource_key).list(**args)
TypeError: list() got an unexpected keyword argument 'cursor'
```

**Comment by hugolgst** [comment]
Did you manage to solve it?

**Comment by savio-tran** [comment]
Have ever find a  solution for this? I'm getting the same error.

**Comment by savio-tran** [comment]
[10/27/2022 10:39:36] Getting next page for users (1000 collected)
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    main()
  File "run.py", line 19, in main
    bot = Bot()
  File "/src/lins05/slackbot/slackbot/bot.py", line 20, in __init__
    self._client = SlackClient(
  File "/src/lins05/slackbot/slackbot/slackclient.py", line 60, in __init__
    self.rtm_connect()
  File "/src/lins05/slackbot/slackbot/slackclient.py", line 65, in rtm_connect
    self.parse_slack_login_data(reply)
  File "/src/lins05/slackbot/slackbot/slackclient.py", line 87, in parse_slack_login_data
    self.parse_user_data(self.list_users())
  File "/src/lins05/slackbot/slackbot/slackclient.py", line 78, in list_users
    return webapi_generic_list(self.webapi, 'users', 'members')
  File "/src/lins05/slackbot/slackbot/slackclient.py", line 30, in webapi_generic_list
    response = getattr(webapi, resource_key).list(**args)
TypeError: list() got an unexpected keyword argument 'cursor'

**Comment by veselyvojtech** [comment]
[This list](https://github.com/os/slacker/blob/3c7f43f75ee838be1121342c1aea1360388015e8/slacker/__init__.py#L330) method of the `Users` class is called here. It doesn't expect the `cursor` argument.
