### ISSUE TITLE
python 3.4 compatible?

### ISSUE THREAD

**Issue by fickas** [scrapinghub/slackbot#26]
Works great in 2.7. Should I expect issues if run under 3.4?

**Comment by DataGreed** [comment]
Why not giving it a try?

sent from a small handheld device with autocorrection
18 сент. 2015 г. 1:45 AM пользователь "fickas" notifications@github.com
написал:

**Comment by lins05** [comment]
I don't think the current code can work with py3k, but would like to see if someone is willing to work on it.

**Comment by timc3** [comment]
The first thing that happened when I tried to install slackbot under pip3 with python3.5 was:

```
root@timdevel:~/bot# pip3 install importlib
Collecting importlib
  Using cached importlib-1.0.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/local/lib/python3.5/site-packages/setuptools/__init__.py", line 4, in <module>
        import distutils.core
      File "/usr/local/lib/python3.5/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/usr/local/lib/python3.5/distutils/dist.py", line 19, in <module>
        from distutils.util import check_environ, strtobool, rfc822_escape
      File "/usr/local/lib/python3.5/distutils/util.py", line 9, in <module>
        import importlib.util
    ImportError: No module named ‘importlib.util’
```

**Comment by timc3** [comment]
A manual download and installation later and running `python3 start.py` gives

```
[user@timdevel bot]# python3 start.py
Traceback (most recent call last):
  File "start.py", line 3, in <module>
    from slackbot.bot import Bot
  File "/usr/local/lib/python3.5/site-packages/slackbot-0.2.4-py3.5.egg/slackbot/bot.py", line 9, in <module>
ImportError: No module named ‘thread’
```

**Comment by timc3** [comment]
So looking at it we might be able to do something like

``` python
try:
   import thread
except ImportError:
   import _thread as thread
```

But then there are other issues, such as syntax being different i.e.. `except WebSocketException, e:`. I will see if I have time to dig into this deeper.

**Comment by merqurio** [comment]
This could be closed ?
