### ISSUE TITLE
Non-wheel pip install fails 

### ISSUE THREAD

**Issue by dangra** [scrapinghub/slackbot#5]
```
~$ mkvirtualenv test-slackbot
New python executable in /home/daniel/envs/test-slackbot/bin/python2
Also creating executable in /home/daniel/envs/test-slackbot/bin/python
Installing setuptools, pip...done.
test-slackbot ~$ pip install --help |grep wheel
  --no-use-wheel              Do not Find and prefer wheel archives when searching indexes and find-links locations.
test-slackbot ~$ pip install --no-use-wheel slackbot 
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting slackbot
  Downloading slackbot-0.1.8.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-RDa_Xl/slackbot/setup.py", line 4, in <module>
        __version__ = open(join(dirname(__file__), 'slackbot/VERSION')).read().strip()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-RDa_Xl/slackbot/slackbot/VERSION'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-RDa_Xl/slackbot/setup.py", line 4, in <module>

        __version__ = open(join(dirname(__file__), 'slackbot/VERSION')).read().strip()

    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-RDa_Xl/slackbot/slackbot/VERSION'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RDa_Xl/slackbot
```

**Comment by dangra** [comment]
Latest package version published to pypi is `v0.1.8` but the github repository is missing the bumpversion commits and corresponding tag. So, latest release didn't use travis-ci to publish pypi packages, that may be the cause of troubles.

**Comment by dangra** [comment]
Another chance is that `slackbot/VERSION` is not shipped anyway, and it is fixable easily with a MANIFEST.in file in project root. 

i.e.: https://github.com/scrapy/scrapy/blob/master/MANIFEST.in#L6

**Comment by lins05** [comment]
I've included the VERSION file in source distribution by adding a `MANIFEST.IN`. Now install from source should work.

Publishing to pypi from travis has never succeeded. Maybe I got something wrong with the encrypted password in [.travis.yml](https://github.com/lins05/slackbot/tree/master/.travis.yml).
